name = "koios-coach"
main = "src/main.ts"
compatibility_date = "2023-12-01"

[site]
bucket = "./assets"

[vars]
OPENAI_API_KEY = "PLACEHOLDER_OPENAI_API_KEY"
PREDICTION_API_URL = "https://koios-api.fly.dev/predictions"
R2_ACCESS_KEY = "PLACEHOLDER_R2_ACCESS_KEY"
R2_SECRET_KEY = "PLACEHOLDER_R2_SECRET_KEY"
CF_ACCOUNT_ID = "PLACEHOLDER_CF_ACCOUNT_ID"
DEEPGRAM_KEY = "PLACEHOLDER_DEEPGRAM_KEY"
DEEPGRAM_URL = "https://api.deepgram.com/v1/listen"
JWT_SECRET = "PLACEHOLDER_JWT_SECRET"
DKIM_DOMAIN = "getkoios.ai"
DKIM_SELECTOR = "mailchannels"
DKIM_PRIVATE_KEY = "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMqYrkaGu5Sc/P3wFbgM1CE15151CqwkmyMKn5deq0Ud7i1IbuheAy/JgCUKtTYDfSwnGFXo1zqW7NOiPMwGEuD6p/9mbxsLx1MEwHPNe4eRiuroDhmXKg8lbjlijqCsqEUhNYuPuko73mJpI2aLmDpgYiiWMUHz+GeKgkQ+UMh+tfatZoJC4OVmbiXmXwtr2q0zsltsBxwOG2BVQS2am+Ay/8LQZBCEckVsiwWcEZtz45L5RA0Gdy98NNBY/5/wGZBmGxkO5CD7sVXX9sFKsavIsIkw/YtmH8KxmlQ6JDM666PFbR9jfHy1h3F3VS+ngXbJEtYF48eEeNEGy/fAWrAgMBAAECggEAU2jno8YQ3S+BY9khrv6z6LGHJmszG5zaNyaRJ4uQr5PMUErIgS6LnIwIkaz53h2RMrKvXGkYIiLT9w0yaPCgyop09PjhpK/gZqxb1/lKe7LSxeJ1wTvuFT0e/1sD6rqiJcJjgx3E5SkcrE9c+JK+xLIlvu6aNCm2FKJY+Iq5L1z9DpeyIDtlDW6998NwYMiIAvp8KmJQLad6IbjXq3ZMntmMG7g6QjsurGpaFPbCovSXA4GRWF3IXpAj3yWDDRKfcBLxag+enaILDvjIr2GPophgrS757jh5NZF7Z1cJPqnoH4+E40Olo+OkoqXO4w5UEf26SaMCsKg7pW/4TM6bsQKBgQDoN58an52dHETKTjtAnpPKdvgLMLsIq7BpcRW3tyZ7/B/qY7GjczC2Jz/yP67jjAfAyMFkXGdo+rPmRn6n+8TpUVbWRSaBFwrM78f0tM+4uoPjsuGEg26LC/g6QQUH8Dc3AX2xGW+ZSXBtJ3NhYL7csvc1yI+PibfM+RjDyxdKUQKBgQDhn3i5Vcr+JQb+K0ceyDIdZNaeb2cgjFDLTH5iU0Z9EFJggu2CkphrSpv3xH25zQJCFemiJ92H7cqauKOIlkylT5C+np/Vv39lTW8D2W5o3THhKHeUjTegvxv9WZeCQVvRPf+ENdblWPBd7QGdHhqzrATekew4llzuIhY6USFVOwKBgQDTRr/4bh7t8elYk0LvsRfQDtvw+n5BDkxsMtpKk1VtWuAC1n+pscUxBZb1piFNoHrxWPYzhKsFZYvGSH82ASiQC1RRkQrOSpOmD8dCijuv2+rhgUAT26z4z4QiJEQai+EAp9efCQBzW9DxTwJ4J5ifniizg22yb9+Nm1l/0ki3cQKBgAltEiwcC3kGrv4bbMM6de2Icvb3jIVtl0qHDZiqBf3fmrFxht63pSqGWXHGgcIrcHa2V6Zwp+6v3pEMObjRHq6hXli4Y9EYSQhAbezpPpWe+CCCAkzwgWxzz4WMIqpMdLuPLYemgC3gw1oJNtILme37t9BcpFPQ5F0Gi4swLIZVAoGAPPGSPZa9CITPXD6tRwRyE+e/HitPw5nVrRfCDahPZ38FgUOxSN01qTewibUzJslwAruGj8RQZylA9aEb8iSCKwce/K81A+dsJKYQFrroWF1apQVapJ+6PGWXVu+/apN1Xf269tSKwczTHT73tjS9eY3w8L85aeBzyle/CdQVbcQ="
VECTOR_STORE_ID = "PLACEHOLDER_VECTOR_STORE_ID"

[[d1_databases]]
binding = "DB"
database_name = "PLACEHOLDER_D1_DB_NAME"
database_id = "PLACEHOLDER_D1_DB_ID"

[[queues.consumers]]
queue = "PLACEHOLDER_QUEUE_NAME"
max_batch_size = 1

[[queues.producers]]
queue = "PLACEHOLDER_QUEUE_NAME"
binding = "QUEUE"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'koios-audio'
